/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.view;

import java.text.DecimalFormat;

/**
 *
 * @author s.lucas
 */
public class FPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FPrincipal
     */
    public FPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnFundo = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        lbNota2 = new javax.swing.JLabel();
        lbNota3 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lbNota1 = new javax.swing.JLabel();
        txtNota1 = new javax.swing.JTextField();
        txtNota2 = new javax.swing.JTextField();
        txtNota3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lbBoletim = new javax.swing.JLabel();
        lbAluno = new javax.swing.JLabel();
        lbRNota1 = new javax.swing.JLabel();
        lbRNota2 = new javax.swing.JLabel();
        lbRNota3 = new javax.swing.JLabel();
        lbResult = new javax.swing.JLabel();
        lbNota3B = new javax.swing.JLabel();
        lbNomeB = new javax.swing.JLabel();
        lbNota1B = new javax.swing.JLabel();
        lbNota2B = new javax.swing.JLabel();
        lbMedia = new javax.swing.JLabel();
        lbMediaR = new javax.swing.JLabel();
        lbAlunoR = new javax.swing.JLabel();
        lbNomeResult = new javax.swing.JLabel();
        lbEsta = new javax.swing.JLabel();
        lbAprov = new javax.swing.JLabel();
        btGerar = new javax.swing.JButton();
        btClean = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnFundo.setBackground(new java.awt.Color(0, 204, 204));

        lbTitulo.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        lbTitulo.setText("GESTOR ESCOLAR");

        lbNome.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        lbNome.setText("Nome do aluno:");

        lbNota2.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        lbNota2.setText("Nota 2:");

        lbNota3.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        lbNota3.setText("Nota 3:");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        lbNota1.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        lbNota1.setText("Nota 1:");

        jPanel1.setBackground(new java.awt.Color(51, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbBoletim.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        lbBoletim.setText("BOLETIM");
        jPanel1.add(lbBoletim, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 11, -1, -1));

        lbAluno.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        lbAluno.setText("Aluno:");
        jPanel1.add(lbAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        lbRNota1.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        lbRNota1.setText("Nota 1:");
        jPanel1.add(lbRNota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        lbRNota2.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        lbRNota2.setText("Nota 2:");
        jPanel1.add(lbRNota2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        lbRNota3.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        lbRNota3.setText("Nota 3:");
        jPanel1.add(lbRNota3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        lbResult.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        lbResult.setText("Resultado");
        jPanel1.add(lbResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 47, -1, -1));

        lbNota3B.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        lbNota3B.setText("???");
        jPanel1.add(lbNota3B, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 60, 30));

        lbNomeB.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        lbNomeB.setText("???");
        jPanel1.add(lbNomeB, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 120, 30));

        lbNota1B.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        lbNota1B.setText("???");
        jPanel1.add(lbNota1B, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 60, 30));

        lbNota2B.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        lbNota2B.setText("???");
        jPanel1.add(lbNota2B, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 60, 30));

        lbMedia.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        lbMedia.setText("Média:");
        jPanel1.add(lbMedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 50, 20));

        lbMediaR.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        lbMediaR.setText("???");
        jPanel1.add(lbMediaR, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 40, 20));

        lbAlunoR.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        lbAlunoR.setText("O aluno ");
        jPanel1.add(lbAlunoR, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, -1));

        lbNomeResult.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        lbNomeResult.setText("???");
        jPanel1.add(lbNomeResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 100, -1));

        lbEsta.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        lbEsta.setText("Está");
        jPanel1.add(lbEsta, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        lbAprov.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        lbAprov.setText("???");
        jPanel1.add(lbAprov, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 80, -1));

        btGerar.setBackground(new java.awt.Color(22, 135, 242));
        btGerar.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        btGerar.setText("Gerar boletim");
        btGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerarActionPerformed(evt);
            }
        });

        btClean.setBackground(new java.awt.Color(208, 26, 21));
        btClean.setFont(new java.awt.Font("Cambria Math", 1, 12)); // NOI18N
        btClean.setText("Limpar");
        btClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCleanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnFundoLayout = new javax.swing.GroupLayout(pnFundo);
        pnFundo.setLayout(pnFundoLayout);
        pnFundoLayout.setHorizontalGroup(
            pnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFundoLayout.createSequentialGroup()
                .addGroup(pnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnFundoLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(pnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnFundoLayout.createSequentialGroup()
                                .addComponent(lbNota1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNota1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbNota2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNota2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbNota3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNota3))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnFundoLayout.createSequentialGroup()
                                .addComponent(lbNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnFundoLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(btGerar)
                        .addGap(18, 18, 18)
                        .addComponent(btClean))
                    .addGroup(pnFundoLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        pnFundoLayout.setVerticalGroup(
            pnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnFundoLayout.createSequentialGroup()
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(pnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(pnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNota2)
                    .addComponent(lbNota3)
                    .addComponent(lbNota1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(pnFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btGerar)
                    .addComponent(btClean))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed

    }//GEN-LAST:event_txtNomeActionPerformed

    private void btCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCleanActionPerformed
        txtNome.setText(null);
        txtNota1.setText(null);
        txtNota2.setText(null);
        txtNota3.setText(null);
    }//GEN-LAST:event_btCleanActionPerformed

    private void btGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerarActionPerformed
        double nota1, nota2, nota3, media;
        DecimalFormat f = new DecimalFormat("0.00");

        lbNomeB.setText(txtNome.getText());
        lbNota1B.setText(txtNota1.getText());
        lbNota2B.setText(txtNota2.getText());
        lbNota3B.setText(txtNota3.getText());
        lbNomeResult.setText(txtNome.getText());
        nota1 = Double.parseDouble(txtNota1.getText());
        nota2 = Double.parseDouble(txtNota2.getText());
        nota3 = Double.parseDouble(txtNota3.getText());
        media = (nota1 + nota2 + nota3) / 3;

        lbMediaR.setText(String.valueOf(f.format(media)));
        if (media >= 7) {
             lbAprov.setText("Aprovado");
        } else {
            lbAprov.setText("Reprovado");
        }
    }//GEN-LAST:event_btGerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClean;
    private javax.swing.JButton btGerar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbAluno;
    private javax.swing.JLabel lbAlunoR;
    private javax.swing.JLabel lbAprov;
    private javax.swing.JLabel lbBoletim;
    private javax.swing.JLabel lbEsta;
    private javax.swing.JLabel lbMedia;
    private javax.swing.JLabel lbMediaR;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbNomeB;
    private javax.swing.JLabel lbNomeResult;
    private javax.swing.JLabel lbNota1;
    private javax.swing.JLabel lbNota1B;
    private javax.swing.JLabel lbNota2;
    private javax.swing.JLabel lbNota2B;
    private javax.swing.JLabel lbNota3;
    private javax.swing.JLabel lbNota3B;
    private javax.swing.JLabel lbRNota1;
    private javax.swing.JLabel lbRNota2;
    private javax.swing.JLabel lbRNota3;
    private javax.swing.JLabel lbResult;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JPanel pnFundo;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNota1;
    private javax.swing.JTextField txtNota2;
    private javax.swing.JTextField txtNota3;
    // End of variables declaration//GEN-END:variables
}
